my_dir <- "/Volumes/GoogleDrive/Mi unidad/CR2021/14CR2021/CASILLAS_APROBADAS/"
ffile <- "CASILLAS.txt"
library(data.table)
BD <- fread(paste0(my_dir, ffile))
names(BD)

# URNA ELECTRÓNICA
table(BD$NOMBRE_ESTADO, BD$CASILLA_CON_URNA_ELECTRONICA)

# LISTA NOMINAL
summary(BD$LISTA_NOMINAL_CASILLA)

# TIPO SECCIÓN: M - MIXTA, R - RURAL Y U - URBANA
tapply(BD$LISTA_NOMINAL_CASILLA, BD$TIPO_SECCION_11dic2020, mean)

# TIPO CASILLA: B - BÁSICA, C - CONTIGUA, E - EXTRAORDINARIA Y S - ESPECIAL
tapply(BD$LISTA_NOMINAL_CASILLA, BD$TIPO_CASILLA, mean)


table(BD$TIPO_CASILLA, BD$TIPO_SECCION_11dic2020)

tapply(BD$LISTA_NOMINAL_CASILLA, 
       paste0(BD$TIPO_CASILLA, BD$TIPO_SECCION_11dic2020), mean)


cor(BD$PADRON_CASILLA, BD$LISTA_NOMINAL_CASILLA)
